<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="QueryHandlers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Restaurant.Management.Shared\Restaurant.Shared.csproj" />
    <ProjectReference Include="..\..\Restaurant.ServiceBus\Restaurant.ServiceBus.csproj" />
    <ProjectReference Include="..\Restaurant.Orchestrator.DTO\Restaurant.Orchestrator.DTO.csproj" />
  </ItemGroup>

</Project>
