<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Restaurant.Management.DTO\Restaurant.Management.DTO.csproj" />
    <ProjectReference Include="..\Restaurant.Management.Handler\Restaurant.Management.Handler.csproj" />
    <ProjectReference Include="..\Restaurant.Management.Shared\Restaurant.Management.Shared.csproj" />
  </ItemGroup>

</Project>
