<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Restaurant.Management.Shared\Restaurant.Shared.csproj" />
    <ProjectReference Include="..\Restaurant.Orchestrator.DTO\Restaurant.Orchestrator.DTO.csproj" />
    <ProjectReference Include="..\Restaurant.Orchestrator.Handler\Restaurant.Orchestrator.Handler.csproj" />
  </ItemGroup>

</Project>
